sudo: false
language: java

cache:
  directories:
  - "$HOME/.cache"

install: true
script: mvn package -DskipTests=true

deploy:
  provider: script
  script: "cp .travis.settings.xml $HOME/.m2/settings.xml && mvn deploy"
  skip_cleanup: true
  on:
    tags: true